[package]
name = "rustos"
version = "0.1.0"
authors = ["gdberrio <guilherme.diazberrio@gmail.com>"]

[dependencies]
bootloader_precompiled = "0.2.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "rustos.json"